### ISSUE TITLE
mm32spin05 variant

### ISSUE THREAD

**Issue by robot-tst** [koendv/MM32SPIN27-Arduino#1]
Thank you for this library. Can this library be adapted for the mm32spin05?

**Comment by koendv** [comment]
On Fri, 21 Jul 2023 18:41:14 -0700
robot-tst ***@***.***> wrote:

> Thank you for this library. Can this library be adapted for the
> mm32spin05?
> 

The library works for the mm32spin27.
The library for mm32spin27 could be used as an example to make a similar library that works for the mm32spin05, mm32spin06, and mm32spin07. 
I would guess it would take perhaps one week to compile small sketches that use pinMode, digitalWrite, and Serial.
Between two weeks and a month for something that is "finished".

koen

**Comment by robot-tst** [comment]
Thanks Koen for your quick feedback and insight.

Will look more into it.

**Comment by koendv** [comment]
OK. There is one thing I forgot to mention: how to download firmware.
If you wish to use [black magic probe](https://github.com/blackmagic-debug/blackmagic) to download firmware to MM32SPIN05, please add the enclosed patch:
[bmp_mm32spin05.txt](https://github.com/koendv/MM32SPIN27-Arduino/files/12138056/bmp_mm32spin05.txt)
With this patch, black magic probe will recognize MM32SPIN05.
I do not have an MM32SPIN05 to test with, but ought to work.

**Comment by robot-tst** [comment]
Great! Thanks again for the info.

**Comment by koendv** [comment]
Support for MM32SPIN05 will go in the next release of black magic probe.
In the meantime, you can get firmware for black magic probe, with MM32SPIN05 support built in, from https://github.com/koendv/blackmagic-firmware/releases/tag/current
